import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} antialiased`}
      >
        <div className="min-h-screen bg-white">
          {/* Header */}
          <header className="bg-white border-b-1 border-gray-300">
            <Link
              href="/"
              className="flex items-center justify-center gap-3 px-6 pt-6 pb-4"
            >
              <Image
                src="/blackv1.png"
                alt="V1 Supplies Co. Logo"
                width={48}
                height={24}
                className="h-8 w-auto"
              />
              <h1 className="text-4xl font-medium font-[family-name:var(--font-playfair-display)]">
                V1 Supply Co.
              </h1>
            </Link>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
